# Default page title
title: Hibernate

# Project id name
project: hibernate

# Default minify settings
css_minifier: disabled
js_minifier: disabled
html_minifier: disabled

# project specific information
projects:
  # Search
  search:
    name: Hibernate Search
    icon: 'icon-search'
    releases:
      - version: 4.4.0.Alpha0
        version_family: 4.4
        date: 2013-07-21
        stable: false
        announcement_url: http://in.relation.to/Bloggers/HibernateSearch430FinalWasSpottedInBoston
        summary: Metadata API, dynamic sharding, simpler Infinispan clustering
      - version: 4.3.0.Final
        version_family: 4.3
        date: 2013-06-08
        stable: true
        announcement_url: http://in.relation.to/Bloggers/HibernateSearch430FinalWasSpottedInBoston
        summary: Synchronous JGroups backend, JBoss AS and EAP modules, Near-Real-Time backend speed improvements, spatial improvements
    sourceforge_url: https://sourceforge.net/projects/hibernate/files/hibernate-search/
    group_id: org.hibernate
    artifact_id: hibernate-search
    reference_doc: http://docs.jboss.org/hibernate/search/
    reference_pdf: hibernate_search_reference.pdf
    getting_started: /search/documentation/getting-started
    license:
      name: LGPL v2.1
      url: https://raw.github.com/hibernate/hibernate-search/master/lgpl.txt
    menu:
      intern:
        - name: About
          href: '/search/'
          css_class: 'icon-fixed-width icon-home'
        - name: Downloads
          href: '/search/downloads/'
          css_class: 'icon-fixed-width icon-cloud-download'
        - name: Documentation
          href: '/search/documentation/'
          css_class: 'icon-fixed-width icon-book'
        - name: FAQ
          href: '/search/faq/'
          css_class: 'icon-fixed-width icon-question'
        - name: Roadmap
          href: '/search/roadmap/'
          css_class: 'icon-fixed-width icon-road'
        - name: Contribute
          href: '/search/contribute/'
          css_class: 'icon-fixed-width icon-beer'
      extern:
        - name: Wiki
          href: 'https://community.jboss.org/en/hibernate/search'
          css_class: 'icon-fixed-width icon-edit'
        - name: Issues
          href: 'https://hibernate.atlassian.net/browse/HSEARCH'
          css_class: 'icon-fixed-width icon-exclamation-sign'
          #  icon-bug only in font-awesome 3.2
        - name: Forum
          href: 'https://forum.hibernate.org'
          css_class: 'icon-fixed-width icon-comments'
        - name: Source code
          href: 'https://github.com/hibernate/hibernate-search'
          css_class: 'icon-fixed-width icon-code'
        - name: CI
          href: 'http://ci.hibernate.org/job/hibernate-search-master/'
          css_class: 'icon-fixed-width icon-stethoscope'
  # Validator
  validator:
    name: Hibernate Validator
    icon: 'icon-check'
    releases:
      - version: 5.1.0.Alpha1
        version_family: 5.1
        date: 2013-04-30
        stable: false
      - version: 5.0.1.Final
        version_family: 5.0
        date: 2013-04-30
        stable: true
      - version: 4.3.1.Final
        version_family: 4.3
        date: 2012-11-12
        stable: true
    sourceforge_url: https://sourceforge.net/projects/hibernate/files/hibernate-validator/
    group_id: org.hibernate
    artifact_id: hibernate-validator
    reference_doc: http://docs.jboss.org/hibernate/validator/
    reference_pdf: hibernate_validator_reference.pdf
    getting_started: /validator/documentation/getting-started
    license:
      name: ASL v2
      url: https://raw.github.com/hibernate/hibernate-validator/master/license.txt
    menu:
      intern:
        - name: About
          href: '/validator/'
          css_class: 'icon-fixed-width icon-home'
        - name: Downloads
          href: '/validator/downloads'
          css_class: 'icon-fixed-width icon-cloud-download'
        - name: Documentation
          href: '/validator/documentation'
          css_class: 'icon-fixed-width icon-book'
      extern:
        - name: Wiki
          href: 'https://community.jboss.org/en/hibernate/validator'
          css_class: 'icon-fixed-width icon-edit'
        - name: Contribute
          href: 'https://community.jboss.org/wiki/ContributingToHibernateValidator'
          css_class: 'icon-fixed-width icon-beer'
        - name: FAQ
          href: 'https://community.jboss.org/wiki/HibernateValidatorFAQ'
          css_class: 'icon-fixed-width icon-question'
        - name: Issues
          href: 'https://hibernate.atlassian.net/browse/HV'
          css_class: 'icon-fixed-width icon-exclamation-sign'
        - name: Forum
          href: 'https://forum.hibernate.org'
          css_class: 'icon-fixed-width icon-comments'
        - name: Source code
          href: 'https://github.com/hibernate/hibernate-validator'
          css_class: 'icon-fixed-width icon-code'
        - name: CI
          href: 'https://hibernate-validator.ci.cloudbees.com/'
          css_class: 'icon-fixed-width icon-stethoscope'
  # Tools
  tools:
    name: Hibernate Tools
    icon: 'icon-tools'
    releases:
    group_id: org.hibernate
    artifact_id: hibernate-tools
    reference_doc: http://docs.jboss.org/hibernate/tools/
    reference_pdf: hibernate_tools_reference.pdf
    license:
      name: LGPL v2.1
      url: https://raw.github.com/hibernate/hibernate-search/master/lgpl.txt
    menu:
      intern:
        - name: About
          href: '/tools/'
          css_class: 'icon-fixed-width icon-home'
      extern:
        - name: Issues
          href: 'https://hibernate.atlassian.net/browse/HBX'
          css_class: 'icon-fixed-width icon-exclamation-sign'
          #  icon-bug only in font-awesome 3.2
        - name: Forum
          href: 'https://forum.hibernate.org'
          css_class: 'icon-fixed-width icon-comments'
        - name: Source code
          href: 'https://github.com/hibernate/hibernate-tools'
          css_class: 'icon-fixed-width icon-code'
 #other projects would come here

# Merge multiple JavaScript files to improve performance
fileMerger:
  enabled: true
  outputFilePath: /javascripts/bootstrap-community.js
  paths:
    - /javascripts/_bootstrap-transition.js
    - /javascripts/_bootstrap-alert.js
    - /javascripts/_bootstrap-button.js
    - /javascripts/_bootstrap-carousel.js
    - /javascripts/_bootstrap-collapse.js
    - /javascripts/_bootstrap-dropdown.js
    - /javascripts/_bootstrap-modal.js
    - /javascripts/_bootstrap-tooltip.js
    - /javascripts/_bootstrap-popover.js
    - /javascripts/_bootstrap-scrollspy.js
    - /javascripts/_bootstrap-tab.js
    - /javascripts/_bootstrap-typeahead.js
    - /javascripts/_bootstrap-affix.js
    - /javascripts/_jbossorg-navbarfix.js
    - /javascripts/_jbossorg-misc.js
    - /javascripts/_jquery-easytabs.js
    - /javascripts/_crisp-scripts.js

# Cache hosted fonts, images and javascript
wget:
  enabled: true
  rerunEach: 86400 # seconds
  timestampFilename: _wget-timestamp
  options:
    - --no-remove-listing
    - -q
    - -r
    - --no-parent
    - -N
    - --reject 'index.html*'
    - -e robots=off
    - --directory-prefix=cache
  urls:
    - http://static.jboss.org/theme/js/libs/jquery/jquery-1.9.1.js
    - http://static.jboss.org/theme/js/libs/jquery/jquery-1.9.1.min.js
    - http://static.jboss.org/theme/js/libs/html5/pre3.6/html5.min.js
    - http://static.jboss.org/theme/js/libs/prettify/188.0.0/prettify.min.js
    - http://static.jboss.org/theme/js/libs/holder/1.9/holder.js
    - http://static.jboss.org/theme/fonts/titilliumtext/
    - http://static.jboss.org/theme/fonts/font-awesome/
    - http://static.jboss.org/theme/images/common/
    - http://static.jboss.org/images/example/
    - http://static.jboss.org/images/hibernate/

asciidoctor:
  :safe: safe
  :attributes:
    #sitename: WriteAdapt
    idprefix: ''
    idseparator: '-'
    sectanchors: ''
    toclevels: 3
    icons: font
    source-highlighter: coderay
    coderay-css: style

# Update resource URLs based on the profile
profiles:
  development:
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jborg_js_url: http://static.jboss.org/theme/js
    project_images_url: /cache/static.jboss.org/images/hibernate
    bootstrap_css_url: /cache/static.hibernate.org/stylesheets/bootstrap-community
    bootstrap_js_url: /cache/static.hibernate.org/javascripts/bootstrap-community
  test:
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jborg_js_url: http://static.jboss.org/theme/js
    project_images_url: /cache/static.jboss.org/images/hibernate
    bootstrap_css_url: /cache/static.hibernate.org/stylesheets/bootstrap-community
    bootstrap_js_url: /cache/static.hibernate.org/javascripts/bootstrap-community
    base_url: http://hibernate.org.beanvalidation.org
  staging:
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jborg_js_url: http://static.jboss.org/theme/js
    project_images_url: http://static.jboss.org/images/example
    bootstrap_css_url: http://static.jboss.org/theme/css/bootstrap-community/2.3.1.0/bootstrap-community
    bootstrap_js_url: http://static.jboss.org/theme/js/libs/bootstrap-community/2.3.1.0/bootstrap-community
    base_url: http://example-stg.jboss.org
  production:
    minified: .min
    css_minifier: enabled
    js_minifier: enabled
    html_minifier: enabled
    jborg_fonts_url: http://static.jboss.org/theme/fonts
    jborg_images_url: http://static.jboss.org/theme/images
    jborg_js_url: http://static.jboss.org/theme/js
    project_images_url: http://static.jboss.org/images/example
    bootstrap_css_url: http://static.jboss.org/theme/css/bootstrap-community/2.3.1.0/bootstrap-community
    bootstrap_js_url: http://static.jboss.org/theme/js/libs/bootstrap-community/2.3.1.0/bootstrap-community
    base_url: http://example.jboss.org
